### PR TITLE
Fix re-subscribing of the same content type on every addition

### LINKED ISSUE #372: Excessive amounts of indexing requests with many entities
**Description**
When creating many entities in succession, the indexing becomes very slow after about 20 entities. 

The context where this bug occured is when creating seeds through the strapi entityService, i.e. about 100 articles one after the other.

I suspect that the bug is in the lifecycle hooks, i think in the following code in line 249 it seems like the lifecycles are registered recursively again and again on each execution of the lifecycle. But I am not sure.

https://github.com/meilisearch/strapi-plugin-meilisearch/blob/6fe6f2fc0fa1a47a03daab84e1843a71db679b44/server/services/meilisearch/connector.js#L249

**Expected behavior**
The submitted indexing should not take much longer than the creation in the database

**Current behavior**
It basically halts after about 20 entries.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

Meilisearch docker stats:
```
CONTAINER ID   NAME          CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
b9738f17773f   api-meili-1   88.73%    253.8MiB / 15.52GiB   1.60%     102MB / 46.7MB   27.8MB / 34.8GB   23
```
While indexing the logs of meilisearch (number of requests for the roughly doubles over time, not quite because the lifecycle registration takes some time):
<details>
<summary>Long logs ahead</summary>

```
[2022-04-09T08:00:29Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/settings HTTP/1.1" 202 124 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006133
[2022-04-09T08:00:29Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004954
[2022-04-09T08:00:29Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 0, number_of_documents: 0 }
[2022-04-09T08:00:29Z INFO  actix_web::middleware::logger] 172.28.0.1 "GET /indexes HTTP/1.1" 200 144 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000188
[2022-04-09T08:00:30Z INFO  actix_web::middleware::logger] 172.28.0.1 "GET /indexes/content/stats HTTP/1.1" 200 65 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000339
[2022-04-09T08:00:38Z INFO  actix_web::middleware::logger] 172.28.0.1 "GET /indexes HTTP/1.1" 200 144 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000303
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003050
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 1 }
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003712
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 2 }
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004048
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006067
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 3 }
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 3 }
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 125 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002465
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 125 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.005497
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.010204
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 4 }
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 4 }
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 4 }
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002273
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002645
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004813
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.005992
[2022-04-09T08:00:46Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.007086
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 5 }
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 5 }
[2022-04-09T08:00:46Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 5 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 5 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002153
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002585
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002368
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002230
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 5 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004893
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004565
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.005373
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.007471
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 6 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 6 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 6 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 6 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 6 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004339
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004411
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 125 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004004
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.005251
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004093
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002567
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002111
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 6 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002541
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004978
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.005474
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004678
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003158
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.010030
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 6 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 6 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002168
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002228
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002375
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003204
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003854
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003581
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004963
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003733
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003050
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003029
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004037
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004087
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003401
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004178
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003347
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006329
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008627
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008355
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.015991
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.017767
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.015025
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 7 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002139
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003673
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.007001
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.010015
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008979
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.005875
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006174
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006563
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006936
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008667
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004242
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008987
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.013862
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.014129
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.012462
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.010101
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.007924
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.007761
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008009
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008593
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008949
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008987
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.004372
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 125 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031178
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031235
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.026502
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031356
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031503
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031511
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 125 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031403
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031678
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031691
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031802
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.031852
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.003488
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 125 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006506
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006281
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.006556
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 125 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.010671
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008283
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.010611
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.010089
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008987
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008540
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.008363
[2022-04-09T08:00:47Z INFO  actix_web::middleware::logger] 172.28.0.1 "POST /indexes/content/documents HTTP/1.1" 202 126 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.009639
[2022-04-09T08:00:47Z INFO  meilisearch_lib::index::updates] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 8 }
```

</details>

After some time, this error is shown excessive amount of times (always the same id):
```
error: Meilisearch could not add entry with id: 369: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

Then after cancelling, this error is shown excessive amount of times (always the same id):
```
error: Meilisearch could not add entry with id: 368: aborted
```

**Environment:**
- OS: Manjaro
- MeiliSearch version: v0.26.1
- strapi-plugin-meilisearch version: v0.6.2
- Browser: Firefox
- Strapi version: v4.1.7

### PR DESCRIPTION
**Pull request by bidoubiwa**
# Pull Request

## What does this PR do?
Fixes #372
Fixes: #384

### CODE REVIEW

**Review by nicolasvienot — DISMISSED** [review]
LGTM! :seal:

You could update the comments for the functions `addOneEntryInMeiliSearch` and `addMultipleEntriesToMeilisearch` and maybe merge them into one function as `addOneEntryInMeiliSearch` checks if there is multiple entries.

Also, in term of naming it would be nice to have the same for `create` and `update` :
`addMultipleEntriesToMeilisearch` -> `addEntriesInMeilisearch`

**Review by alallema — APPROVED** [review]
LGTM! 🌮

File: server/services/lifecycle/lifecycle.js [hunk 1]
```diff
@@ -24,9 +24,9 @@ module.exports = ({ strapi }) => {
             .service('meilisearch')
 
           meilisearch
-            .addOneEntryInMeiliSearch({
+            .addEntriesInMeilisearch({
```
Comment (nicolasvienot) [inline server/services/lifecycle/lifecycle.js:27]: Should be `addEntriesToMeilisearch` 😄

**Comment by bidoubiwa** [comment]
bors merge
